--IN PROGRESS 
CREATE OR REPLACE TABLE TB_FONE OF TP_FONE(--Criando o tipo de telefone para depois criar NT
    
);
/
CREATE OR REPLACE TABLE TB_FONES AS VARRAY(5) OF TP_FONE;
/
CREATE OR REPLACE TABLE TB_ENDERECO OF TP_ENDERECO(
    
);
/


CREATE TABLE TB_PESSOA OF TP_PESSOA(
    CPF PRIMARY KEY,
    NOME_PESSOA NOT NULL
);
/
CREATE OR REPLACE TABLE TB_FUNCIONARIO OF TP_FUNCIONARIO(
    
);
/
CREATE OR REPLACE TABLE TB_CINEMA OF TP_CINEMA(
    
);
/
CREATE OR REPLACE TABLE TB_SETOR OF TP_SETOR(
    
);
/
CREATE OR REPLACE TABLE TB_SETOR_FUNC OF TP_SETOR_FUNC( 
   
);
/
CREATE OR REPLACE TABLE TB_TRABALHA OF TP_TRABALHA(
    
);
/
CREATE OR REPLACE TABLE TB_SNACK_BAR OF TP_SNACK_BAR(
   
);
/
CREATE OR REPLACE TABLE TB_PRODUTO OF TP_PRODUTO(
    
);
/
CREATE OR REPLACE TABLE TB_SALA OF TP_SALA(
    
);
/
CREATE OR REPLACE TABLE TB_ATOR OF TP_ATOR(
    
);
/
CREATE OR REPLACE TABLE TB_NT_ATOR OF TP_ATOR;
/
CREATE TABLE TB_FILME OF TP_FILM( 
    ID_FILME PRIMARY KEY, 
    Diretor NOT NULL, 
    Nome_Filme NOT NULL 
)NESTED TABLE Atores STORE AS TB_ATORES;
/
CREATE OR REPLACE TABLE TB_FILME_SALA OF TP_FILME_SALA(
    
);
/

CREATE OR REPLACE TABLE TB_INGRESSO OF TP_INGRESSO(
   
);
/
CREATE OR REPLACE TABLE TB_VENDE_INGRESSO OF TP_VENDE_INGRESSO(
    
);
/
CREATE OR REPLACE TABLE TB_EXIBE OF TP_EXIBE(
    
);
/
