DROP TYPE TP_PESSOA FORCE;
CREATE OR REPLACE TYPE TP_FONE AS OBJECT(--Criando o tipo de telefone para depois criar NT
    NUMERO NUMBER
);
/
CREATE OR REPLACE TYPE TP_ENDEREÇO AS OBJECT(
    CEP VARCHAR2(9),
    RUA VARCHAR2(30),
    BAIRRO VARCHAR2(30),
    CIDADE VARCHAR2(30),
    NUMERO_ENDERECO NUMBER,
);
/
CREATE OR REPLACE TYPE TP_PESSOA AS OBJECT(
    CPF NUMBER,
    NOME_PESSOA VARCHAR2(30) NOT NULL,
    DATA_NASC DATE,
    --Local onde estará a NT de telefone,
    ENDERECO TP_ENDEREÇO
)NOT FINAL;
/
CREATE OR REPLACE TYPE TP_FUNCIONARIO UNDER TP_PESSOA(
    ID_FUNCIONARIO NUMBER NOT NULL,
    ID_SUPERVISOR NUMBER,
    SALARIO DECIMAL(6,2)
);--Não tenho certeza se seria dessa forma, 
/
CREATE TABLE TB_PESSOA OF TP_PESSOA(
    CPF PRIMARY KEY
);
/
CREATE TABLE TB_FUNCIONARIO OF TP_FUNCIONARIO(
    ID_FUNCIONARIO PRIMARY KEY
);
--
