DROP TYPE TP_PESSOA FORCE;
CREATE OR REPLACE TYPE TP_FONE AS OBJECT(--Criando o tipo de telefone para depois criar NT
    NUMERO NUMBER
);
/
CREATE OR REPLACE TYPE TP_PESSOA AS OBJECT(
    CPF NUMBER,
    NOME_PESSOA VARCHAR2(30) NOT NULL,
    DATA_NASC DATE,
    --Local onde estará a NT de telefone
);
/
CREATE TABLE TB_PESSOA OF TP_PESSOA(
    CPF PRIMARY KEY
);
